---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.16.4

platforms:
  - name: debian
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: debian-7-chef
      box_url: http://bit.ly/1weDdiJ
      network:
        - ['private_network', {ip: '172.28.128.3'}]
      customize:
        memory: 512
        cpus: 1

provisioner:
  name: chef_solo

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[apt::default]
      - recipe[devops::default]
    attributes:
      devops:
        chef_domain: 'chef.repository.dev'
        vagrant_domain: 'vagrant.repository.dev'
        software_domain: 'software.repository.dev'
        preseed_domain: 'preseed.repository.dev'
        kickstart_domain: 'kickstart.repository.dev'
        yum_rhel_domain: 'yum.rhel.repository.dev'
        yum_oel_domain: 'yum.oel.repository.dev'
        yum_centos_domain: 'yum.centos.repository.dev'
