name 'devops'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures devops'
long_description 'Installs/Configures devops'
version '0.1.0'
